version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bilal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applewatch
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bilal:password@db:5432/applewatch